server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:./doc
        git:
          uri: file:./doc/gitrepo
          
logging:
  level:
    com.netflix.discovery: 'INFO'
    org.springframework.cloud: 'DEBUG'          

    